server:
  port: 8011

spring:
  application:
    name: spring-boot-rabbitmq-consumer
  rabbitmq:
    host: 192.168.0.131
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual